# Generated by Django 5.0.2 on 2024-04-23 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickchatapp', '0010_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='img/default.webp', null=True, upload_to='img'),
        ),
    ]
